model:
  base_learning_rate: 5.0e-06
  target: ldm.models.diffusion.audioldm.LatentDiffusion
  max_epochs: 1
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "mel"
    cond_stage_key: "audio"
    channels: 4
    cond_stage_trainable: false   # Note: different from the one we trained before
    conditioning_key: film
    monitor: val/loss_simple_ema
    scale_factor: 0.18215

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 10000 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: ldm.modules.diffusionmodules.FiLM_openaimodel.UNetModel
      params:
        image_size: 32
        extra_film_condition_dim: 512
        extra_film_use_concat: True
        in_channels: 4
        out_channels: 4
        model_channels: 128
        attention_resolutions: [ 8, 4, 2 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4]
        num_head_channels: 32
        use_spatial_transformer: True

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ckpt_path: "/data/home/scv9359/run/Code/stable-diffusion/logs/2023-04-26T11-00-39_melvae/checkpoints/epoch=000014.ckpt"
        lossconfig:
          target: ldm.modules.losses.LPIPSWithDiscriminator
          params:
            disc_start: 50001
            kl_weight: 1
            disc_weight: 0.5
            disc_in_channels: 1
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0

    cond_stage_config:
      target: ldm.modules.CLAPencoders.modules.FrozenClapAudioEmbedder

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 7
    num_workers: 4

    train:
      target: ldm.data.audioset_ldm.AudioSetSpecsTrain
      params:
        filedir: '/data/home/scv9359/run/data/audiocaps'
        filename: 'train.txt'
        filetype: 'train'

    validation:
      target: ldm.data.audioset_ldm.AudioSetSpecsValidation
      params:
        filedir: '/data/home/scv9359/run/data/audiocaps'
        filename: 'val.txt'
        filetype: 'val'


lightning:
  # callbacks:
  #   image_logger:
  #     target: main.ImageLogger
  #     params:
  #       batch_frequency: 5000
  #       max_images: 1
  #       increase_log_steps: False
  #       log_first_step: True


  trainer:
    #replace_sampler_ddp: False
    benchmark: True
    every_n_epochs: 1
    # val_check_interval: 400
    # num_sanity_val_steps: 0
