model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 4
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.1
        disc_weight: 0.5
        disc_in_channels: 1

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 256
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

data:
  target: main.SpectrogramDataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 4

    data_path: '/work100/chenrenmiao/data/libritts/LibriTTS/train-clean-100'
    total_num: 10000
    duration: 2.98
    # sample_rate: 22050
    # mel_num: 80
    # spec_len: 860
    # spec_crop_len: 848
    # random_crop: False

    train:
      target: ldm.data.libritts.LibriTTSSpecsTrain
      params:
        specs_dataset_cfg:
    validation:
      target: ldm.data.libritts.LibriTTSSpecsValidation
      params:
        specs_dataset_cfg:

  # trainer:
  #   benchmark: True
  #   accumulate_grad_batches: 2